development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: postgres
  password: secret

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: postgres
  password: secret
  
production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: postgres
  password: secret
